In [13]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# Загрузка данных MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Разделение обучающей выборки на обучающую и проверочную
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1, random_state=42)

print(f"Размер обучающей выборки: {x_train.shape[0]}")
print(f"Размер проверочной выборки: {x_val.shape[0]}")
print(f"Размер тестовой выборки: {x_test.shape[0]}")

# Преобразование данных
x_train = x_train.reshape(x_train.shape[0], -1) / 255.0
x_test = x_test.reshape(x_test.shape[0], -1) / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Архитектура сети 1
print('Архитектура сети 1')
model = Sequential()
model.add(Dense(10, input_dim=784, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10, validation_split=0.1)
_, test_acc = model.evaluate(x_test, y_test)
print(test_acc)

# Архитектура сети 2
print('Архитектура сети 2')
model2 = Sequential()
model2.add(Dense(50, input_dim=784, activation='relu'))
model2.add(Dense(10, activation='softmax'))
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model2.fit(x_train, y_train, epochs=10, validation_split=0.1)
_, test_acc2 = model2.evaluate(x_test, y_test)
print(test_acc2)

# Архитектура сети 3
print('Архитектура сети 3')
model3 = Sequential()
model3.add(Dense(50, input_dim=784, activation='relu'))
model3.add(Dense(50, activation='relu'))
model3.add(Dense(10, activation='softmax'))
model3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model3.fit(x_train, y_train, epochs=10, validation_split=0.1)
_, test_acc3 = model3.evaluate(x_test, y_test)
print(test_acc3)

Размер обучающей выборки: 54000
Размер проверочной выборки: 6000
Размер тестовой выборки: 10000
Архитектура сети 1
Epoch 1/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7140 - loss: 0.8979 - val_accuracy: 0.9124 - val_loss: 0.3058
Epoch 2/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9131 - loss: 0.3055 - val_accuracy: 0.9185 - val_loss: 0.2770
Epoch 3/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9229 - loss: 0.2733 - val_accuracy: 0.9226 - val_loss: 0.2617
Epoch 4/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9260 - loss: 0.2613 - val_accuracy: 0.9328 - val_loss: 0.2435
Epoch 5/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9317 - loss: 0.2453 - val_accuracy: 0.9309 - val_loss: 0.2408
Epoch 6/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9314 - loss: 0.2404 - val_accuracy: 0.9343 - val_loss: 0.2395
Epoch 7/10
1519/1519 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9360 - loss: 0.2322 - val_accuracy: 0

In [14]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.datasets import fashion_mnist
import numpy as np

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train[:,:,:,np.newaxis] / 255.0
x_test = x_test[:,:,:,np.newaxis] / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Архитектура сети 4
print('Архитектура сети 4')
model4 = Sequential()
model4.add(Conv2D(filters=64, kernel_size=2, padding='same', activation='relu', input_shape=(28,28, 1)))
model4.add(MaxPooling2D(pool_size=2))
model4.add(Flatten())
model4.add(Dense(10, activation='softmax'))
model4.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model4.fit(x_train, y_train, epochs=10, validation_split=0.1)
_, test_acc4 = model4.evaluate(x_test, y_test)
print(test_acc4)

Архитектура сети 4


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 39s 22ms/step - accuracy: 0.7956 - loss: 0.5828 - val_accuracy: 0.8768 - val_loss: 0.3509
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 37s 22ms/step - accuracy: 0.8873 - loss: 0.3207 - val_accuracy: 0.8925 - val_loss: 0.3008
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 41s 22ms/step - accuracy: 0.8998 - loss: 0.2838 - val_accuracy: 0.8945 - val_loss: 0.2908
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 41s 22ms/step - accuracy: 0.9066 - loss: 0.2623 - val_accuracy: 0.8978 - val_loss: 0.2898
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 41s 22ms/step - accuracy: 0.9099 - loss: 0.2482 - val_accuracy: 0.9035 - val_loss: 0.2719
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 41s 22ms/step - accuracy: 0.9181 - loss: 0.2261 - val_accuracy: 0.9025 - val_loss: 0.2663
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 36s 21ms/step - accuracy: 0.9211 - loss: 0.2191 - val_accuracy: 0.9077 - val_loss: 0.2661
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 36s 21ms/step - accuracy: 0.9265 -



1.   Архитектура 3 оказалась самой точной.
2.   Архитектуры можно улучшить путем увеличения размерности выходного пространства (Dense(n, input_dim=784, activation='relu'))




In [11]:
import numpy as np

# Функция активации (логистический сигмоид)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Производная сигмоида
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Параметры
X = np.array([0.4, -0.8, 0.2]) # Входной вектор
W1 = np.array([[0.1, -0.2, 0.05], [-0.05, 0.25, -0.1], [0.2, -0.1, 0.3]]) # Матрица синапсов 1 слоя
W2 = np.array([[0.4, -0.7], [1.2, 0.6], [0.1, 0.5]]) # Матрица синапсов 2 слоя + убрана [-1.4, 0.5] т.к. матрица 3х2
Y = np.array([0.5, 0.3]) # Эталонный выход
learning_rate = 0.25 # Скорость обучения

# Прямое распространение
net_h = np.dot(X, W1)
out_h = sigmoid(net_h)

net_o = np.dot(out_h, W2)
out_o = sigmoid(net_o)

# Вычисление ошибки
error = Y - out_o

# Обратное распространение
delta_o = error * sigmoid_derivative(net_o)
delta_h = np.dot(delta_o, W2.T) * sigmoid_derivative(net_h)

# Обновление весов
W2 = W2 + learning_rate * np.outer(out_h, delta_o) #Используем outer для корректного произведения векторов
W1 = W1 + learning_rate * np.outer(X, delta_h) #Используем outer для корректного произведения векторов

# Вывод результатов
print("Выход сети:", out_o)
print("Ошибка:", error)
print("Обновленная матрица весов W1:\n", W1)
print("Обновленная матрица весов W2:\n", W2)


Выход сети: [0.68495682 0.5385029 ]
Ошибка: [-0.18495682 -0.2385029 ]
Обновленная матрица весов W1:
 [[ 0.10063585 -0.20204019  0.04916468]
 [-0.0512717   0.25408039 -0.09832935]
 [ 0.20031793 -0.1010201   0.29958234]]
Обновленная матрица весов W2:
 [[ 0.39471202 -0.70785303]
 [ 1.19575379  0.59369407]
 [ 0.09461273  0.49199952]]
